// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm_Nt9Qf7uN5l2Ng8qV6EfC0YnN3C4L5M',
    appId: '1:123456789012:web:abcdef123456789012',
    messagingSenderId: '123456789012',
    projectId: 'notitest-f010f',
    authDomain: 'notitest-f010f.firebaseapp.com',
    storageBucket: 'notitest-f010f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1b2C3d4E5f6G7h8I9j0K1l2M3n4O5p6Q',
    appId: '1:123456789012:android:abcdef123456789012',
    messagingSenderId: '123456789012',
    projectId: 'notitest-f010f',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyZ9Y8X7W6V5U4T3S2R1Q0P9O8N7M6L5K4J',
    appId: '1:123456789012:ios:abcdef123456789012',
    messagingSenderId: '123456789012',
    projectId: 'notitest-f010f',
    iosBundleId: 'com.example.notify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyZ9Y8X7W6V5U4T3S2R1Q0P9O8N7M6L5K4J',
    appId: '1:123456789012:ios:abcdef123456789012',
    messagingSenderId: '123456789012',
    projectId: 'notitest-f010f',
    iosBundleId: 'com.example.notify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBm_Nt9Qf7uN5l2Ng8qV6EfC0YnN3C4L5M',
    appId: '1:123456789012:web:abcdef123456789012',
    messagingSenderId: '123456789012',
    projectId: 'notitest-f010f',
    authDomain: 'notitest-f010f.firebaseapp.com',
    storageBucket: 'notitest-f010f.appspot.com',
  );
}
